export default {
  async fetch(request, env, ctx) {
    const corsHeaders = {
      "Access-Control-Allow-Origin": "*",
      "Access-Control-Allow-Methods": "GET, HEAD, OPTIONS",
      "Access-Control-Allow-Headers": "*",
    };

    if (request.method === "OPTIONS") {
      return new Response(null, { headers: corsHeaders });
    }

    const requestUrl = new URL(request.url);
    const targetUrl = requestUrl.searchParams.get("url");

    if (!targetUrl) {
      return new Response(
        JSON.stringify({
          status: "error",
          message: "Video URL parameter missing.",
          usage: `${requestUrl.origin}/?url=https://streamtape.com/e/VIDEO_ID/`
        }, null, 2),
        {
          status: 400,
          headers: { ...corsHeaders, "Content-Type": "application/json; charset=utf-8" },
        }
      );
    }

    try {
      // 1. Extract Video ID
      const idMatch = targetUrl.match(/\/(?:v|e)\/([a-zA-Z0-9]+)/);
      if (!idMatch) {
        return new Response(
          JSON.stringify({ status: "error", message: "Invalid Streamtape URL format." }, null, 2),
          { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json; charset=utf-8" } }
        );
      }

      const videoId = idMatch[1];
      const embedUrl = `https://streamtape.to/e/${videoId}`;

      const clientIp = request.headers.get("CF-Connecting-IP") || "127.0.0.1";
      const browserHeaders = {
        "User-Agent":
          "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36",
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
        "Accept-Language": "en-US,en;q=0.9",
        "Referer": embedUrl,
        "X-Forwarded-For": clientIp,
        "CF-Connecting-IP": clientIp,
      };

      // 2. Fetch Embed HTML Page
      const embedRes = await fetch(embedUrl, {
        headers: browserHeaders,
        redirect: "follow",
      });

      if (!embedRes.ok) {
        return new Response(
          JSON.stringify({ status: "error", message: `Upstream error: HTTP ${embedRes.status}` }, null, 2),
          { status: 502, headers: { ...corsHeaders, "Content-Type": "application/json; charset=utf-8" } }
        );
      }

      const html = await embedRes.text();

      if (html.includes("Video not found") || html.includes("File was deleted")) {
        return new Response(
          JSON.stringify({ status: "error", message: "Video not found or file deleted." }, null, 2),
          { status: 404, headers: { ...corsHeaders, "Content-Type": "application/json; charset=utf-8" } }
        );
      }

      // 3. Robust JavaScript String-Slicing Parser
      let gateUrl = null;

      // Extract all script lines that set innerHTML with a dynamic get_video link
      const scriptLines = html.match(/document\.getElementById\([^)]+\)\.innerHTML\s*=\s*[^;\n]+;/g) || [];

      // Filter only those lines containing get_video
      const targetLines = scriptLines.filter(line => line.includes("get_video"));

      if (targetLines.length > 0) {
        // The genuine token is always generated by the last assignment
        const lastLine = targetLines[targetLines.length - 1];

        // Match string inside parentheses: ('...tape.to/get_video?id=...')
        const rawStringMatch = lastLine.match(/\(\s*['"]([^'"]*tape\.to\/get_video\?[^'"]+)['"]\s*\)/);
        
        // Extract all .substring(X) in execution order
        const substringMatches = [...lastLine.matchAll(/\.substring\((\d+)\)/g)];

        if (rawStringMatch) {
          let resolvedStr = rawStringMatch[1];
          for (const m of substringMatches) {
            const offset = parseInt(m[1], 10);
            resolvedStr = resolvedStr.substring(offset);
          }

          // Prefix with https://
          gateUrl = "https://" + resolvedStr.replace(/^\/+/, "");
        }
      }

      // Universal Fallback: scan any token string followed by substring chain
      if (!gateUrl) {
        const genericMatch = html.match(/['"]([^'"]*tape\.to\/get_video\?[^'"]+)['"]\s*\)((\s*\.substring\(\d+\))+)/);
        if (genericMatch) {
          let resolvedStr = genericMatch[1];
          const chain = [...genericMatch[2].matchAll(/\.substring\((\d+)\)/g)];
          for (const m of chain) {
            resolvedStr = resolvedStr.substring(parseInt(m[1], 10));
          }
          gateUrl = "https://" + resolvedStr.replace(/^\/+/, "");
        }
      }

      if (!gateUrl) {
        return new Response(
          JSON.stringify({
            status: "error",
            message: "Could not decode dynamic token string from script.",
            found_lines: targetLines
          }, null, 2),
          { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json; charset=utf-8" } }
        );
      }

      if (!gateUrl.includes("stream=1")) {
        gateUrl += "&stream=1";
      }

      // 4. Resolve Final Tapecontent CDN Link
      const gateHeaders = {
        "User-Agent": browserHeaders["User-Agent"],
        "Accept": "*/*",
        "Referer": embedUrl,
      };

      const gateRes = await fetch(gateUrl, {
        headers: gateHeaders,
        redirect: "follow",
      });

      const finalCdnUrl = gateRes.url;

      // 5. Output Pure Clean JSON
      return new Response(
        JSON.stringify({
          status: "success",
          video_id: videoId,
          real_gate_url: gateUrl,
          direct_cdn_url: finalCdnUrl,
          timestamp: new Date().toISOString()
        }, null, 2),
        {
          status: 200,
          headers: {
            ...corsHeaders,
            "Content-Type": "application/json; charset=utf-8",
            "Cache-Control": "no-store, no-cache, must-revalidate",
          },
        }
      );

    } catch (err) {
      return new Response(
        JSON.stringify({ status: "error", message: err.message }, null, 2),
        { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json; charset=utf-8" } }
      );
    }
  },
};
